DO $$
BEGIN
  ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'REASSIGNED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'WAITING_ASSISTANCE';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
