import { Robot, Task, Session } from './types';

export const ROBOTS: Robot[] = [
  {
    id: 'R01',
    name: 'Sinoe Prime',
    status: 'active',
    position: [124.5, 88.2],
    capacity: '40 units / 180kg',
    objective: 'Dock Alpha-4',
    type: 'manufacturing',
    battery: 94,
  },
  {
    id: 'R02',
    name: 'Alison Vector',
    status: 'waiting',
    position: [45.1, 212.8],
    capacity: '40 units / 180kg',
    objective: 'Waiting for Queue',
    type: 'rocket',
    battery: 62,
  },
  {
    id: 'R03',
    name: 'Mira Core',
    status: 'maintenance',
    position: [0, 0],
    capacity: 'Offline',
    objective: 'Diagnostic Check',
    type: 'memory',
    battery: 12,
  },
  {
    id: 'R04',
    name: 'Nova Shadow',
    status: 'inactive',
    position: [0, 0],
    capacity: '40 units / 180kg',
    objective: 'Idle',
    type: 'manufacturing',
    battery: 0,
  },
  {
    id: 'R05',
    name: 'Titan X',
    status: 'disconnected',
    position: [8.4, 19.2],
    capacity: '32 units / 145kg',
    objective: 'Link lost 14m ago',
    type: 'power',
    battery: 0,
  },
];

export const TASKS: Task[] = [
  {
    id: 'TX-9023',
    title: 'MOVE LIQUID BULK',
    description: 'Automated conveyance task for high-volume units.',
    priority: 'high',
    status: 'in-progress',
    origin: 'SEC-A, Bay 04',
    originCoords: [34.22, -118.04],
    destination: 'Packaging Wing',
    destCoords: [34.25, -118.10],
    loadDetails: 'Liquid Nitrogen (500L)',
    requirements: ['Frágil', 'Refrigeración'],
    progress: 50,
    stage: 'Carga (Step 2/4)',
  },
  {
    id: 'TX-8812',
    title: 'HEAVY MACHINERY TRANSPORT',
    description: 'Transporting industrial press to Sector 4.',
    priority: 'normal',
    status: 'pending',
    origin: 'Main Bay',
    originCoords: [4, 1],
    destination: 'Sector 4 Assembly',
    destCoords: [4, 15],
    loadDetails: '2500kg / Industrial Press',
    requirements: ['Heavy Load', 'Oversized'],
    progress: 5,
    stage: 'Queueing',
  },
  {
    id: 'TX-9104',
    title: 'HAZARDOUS WASTE DISPOSAL',
    description: 'Maintenance protocol across Sector 7.',
    priority: 'high',
    status: 'in-progress',
    origin: 'ALL',
    originCoords: [0, 0],
    destination: 'LAB_G4',
    destCoords: [14, 88],
    loadDetails: 'Biohazard / Gaseous',
    requirements: ['Biohazard', 'Level 4 Clearance'],
    progress: 85,
    stage: 'Inert Gas Spray',
  },
];

export const SESSIONS: Session[] = [
  {
    id: 'PC-B01',
    name: 'Panel Central',
    status: 'active',
    ip: '192.168.1.104',
    loginTime: '12/05/2024 08:42:12',
    mac: '48:2C:6A:1E:59:B0',
    os: 'Industrial-OS v4.2',
  },
  {
    id: 'M-04',
    name: 'Mobile Controller M-04',
    status: 'secondary',
    ip: '192.168.1.215',
    loginTime: '12/05/2024 08:38:00',
  },
  {
    id: 'SSH-A',
    name: 'Remote SSH Terminal (Bldg-A)',
    status: 'secondary',
    ip: '10.0.4.12',
    loginTime: '12/05/2024 08:30:00',
  },
];
